In [ ]:
import pandas as pd
import pickle
from tqdm import tqdm
import re
from wordcloud import WordCloud, STOPWORDS

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
#import spacy

In [ ]:
import locale
locale.getdefaultlocale()

('en_US', 'UTF-8')

In [ ]:
print(locale.getpreferredencoding())

ANSI_X3.4-1968

In [ ]:
def getpreferredencoding(do_setlocale = True):
    return "UTF-8"
locale.getpreferredencoding = getpreferredencoding

In [ ]:
!pip install transformers
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.26.1-py3-none-any.whl (6.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 93.2 MB/s eta 0:00:00
Collecting huggingface-hub<1.0,>=0.11.0
  Downloading huggingface_hub-0.12.1-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.3/190.3 KB 23.1 MB/s eta 0:00:00
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from transformers) (2.25.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from transformers) (6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (1.22.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.8/dist-packages (from transformers) (23.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.8/dist-packages (from transformers) (2022.6.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from transformers) (3.9.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.8/dist-packages (from transformers) (4.64.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
  Downloading tokenizers-0.13.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 114.2 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0,>=0.11.0->transformers) (4.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->transformers) (2.10)
Installing collected packages: tokenizers, huggingface-hub, transformers
Successfully installed huggingface-hub-0.12.1 tokenizers-0.13.2 transformers-4.26.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting datasets
  Downloading datasets-2.10.1-py3-none-any.whl (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 KB 33.0 MB/s eta 0:00:00
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /usr/local/lib/python3.8/dist-packages (from datasets) (0.3.6)
Collecting multiprocess
  Downloading multiprocess-0.70.14-py38-none-any.whl (132 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.0/132.0 KB 18.2 MB/s eta 0:00:00
Requirement already satisfied: pyarrow>=6.0.0 in /usr/local/lib/python3.8/dist-packages (from datasets) (9.0.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.8/dist-packages (from datasets) (2.25.1)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /usr/local/lib/python3.8/dist-packages (from datasets) (2023.1.0)
Collecting responses<0.19
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Collecting xxhash
  Downloading xxhash-3.2.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (213 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 213.0/213.0 KB 26.2 MB/s eta 0:00:00
Requirement already satisfied: huggingface-hub<1.0.0,>=0.2.0 in /usr/local/lib/python3.8/dist-packages (from datasets) (0.12.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.8/dist-packages (from datasets) (6.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.8/dist-packages (from datasets) (1.22.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from datasets) (23.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from datasets) (1.3.5)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.8/dist-packages (from datasets) (3.8.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.8/dist-packages (from datasets) (4.64.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (3.0.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (22.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (1.8.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.8/dist-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (4.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.8/dist-packages (from huggingface-hub<1.0.0,>=0.2.0->datasets) (3.9.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->datasets) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->datasets) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->datasets) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas->datasets) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.15.0)
Installing collected packages: xxhash, multiprocess, responses, datasets
Successfully installed datasets-2.10.1 multiprocess-0.70.14 responses-0.18.0 xxhash-3.2.0

In [ ]:
from transformers import pipeline
from datasets import Dataset

In [ ]:
classifier = pipeline("sentiment-analysis",model='neuraly/bert-base-italian-cased-sentiment',truncation=True,
    max_length=512,device=0)

Downloading (…)lve/main/config.json:   0%|          | 0.00/1.29k [00:00<?, ?B/s]

Downloading (…)"pytorch_model.bin";:   0%|          | 0.00/443M [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/40.0 [00:00<?, ?B/s]

Downloading (…)solve/main/vocab.txt:   0%|          | 0.00/235k [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
classifier.batch_size = 100  # increase the batch size to reduce the number of batches
classifier.model.config.max_length = 512  # increase the sequence length to process longer texts

In [ ]:
#!python -m spacy download it_core_news_lg

In [ ]:
filename='/content/drive/MyDrive/AI/data/litigi.pickle'

In [ ]:
fp=open(filename,'rb')
litigi=pickle.load(fp)
fp.close()

In [ ]:
tqdm.pandas()

In [ ]:
#nlp = spacy.load('it_core_news_lg')

OSError: ignored

In [ ]:
#doc = nlp("	Number one: perle è uno state of mind, non un subreddit. Non ce ne frega un cazzo che non sei in grado di seguire le regole di un subreddit, per quanto stupide. Fondati il tuo e vedi. Ah, già: lo hai fatto e non ti si incula nessuno. Number two: la lista dei moderatori è visibile nella front page di ogni subreddit. Usi roba tipo script, python e cazzi pitonati e non sai come recuperare queste informazioni base? Chi vuoi prendere per il culo? La verità (come ho detto già in passato) è che sei un drogato di attenzione, faresti di tutto per avere mezza interazione. Il problema è che sei tremendamente banale e noioso, la cosa più stimolante che riesci a fare è spammare un brusio continuo di merda insignificante finche qualcuno (me in questo caso) non smatta e ti risponde più per sfinimento che per pietà. Vaffanculo Pietro, se avessi un minimo di saggezza, lavoreresti su te stesso. Mi fai rimpiangere i mentecatti del covid, renditi conto. Sei solo chiacchiera indistinta, l'incubo di Heidegger.")
#displacy.render(doc, style="ent",jupyter=True)

In [ ]:

def preprocess(text):
    # Matches any string that starts with '[' and ends with ']' followed by '(', any non-space character, and ')'
    url_pattern = r'\[(.+?)\]\(.*?\S.*?\)'
    # Replaces any matches with the captured text between the square brackets
    text = re.sub(url_pattern, r'\1', text)
    #should remove quotes: anythong between > and \n\n
    quote_pattern= r'\>(.+?)\\n\\n'
    text=re.sub(quote_pattern,'',text)
    #remove \n
    text=text.replace('\\n', ' ').replace('\n', ' ').replace('\t',' ').replace('\\', ' ')
    return text

In [ ]:
litigi['body_preprocessed']=litigi['body'].apply(lambda x: preprocess(x))

In [ ]:
classifier("Number one: perle è uno state of mind, non un subreddit. Non ce ne frega un cazzo che non sei in grado di seguire le regole di un subreddit, per quanto stupide. Fondati il tuo e vedi. Ah, già: lo hai fatto e non ti si incula nessuno. Number two: la lista dei moderatori è visibile nella front page di ogni subreddit. Usi roba tipo script, python e cazzi pitonati e non sai come recuperare queste informazioni base? Chi vuoi prendere per il culo? La verità (come ho detto già in passato) è che sei un drogato di attenzione, faresti di tutto per avere mezza interazione. Il problema è che sei tremendamente banale e noioso, la cosa più stimolante che riesci a fare è spammare un brusio continuo di merda insignificante finche qualcuno (me in questo caso) non smatta e ti risponde più per sfinimento che per pietà. Vaffanculo Pietro, se avessi un minimo di saggezza, lavoreresti su te stesso. Mi fai rimpiangere i mentecatti del covid, renditi conto. Sei solo chiacchiera indistinta, l'incubo di Heidegger.")

[{'label': 'negative', 'score': 0.9963662624359131}]

In [ ]:
litigi[['body_preprocessed','body','author']]

,body_preprocessed,body,author
0,Qualcosa da spaccare?,Qualcosa da spaccare?,Trickyhere
1,"Avevo quest'ideona dello sticky giornaliero ""A...","Avevo quest'ideona dello sticky giornaliero ""A...",panicClark
2,"Risposta USENET: ""non l'avete capita"" (cit.) ...","Risposta USENET: ""non l'avete capita"" (cit.)\n...",MeccAnon
3,GENIO.,[GENIO.](https://www.reddit.com/r/litigi/comme...,panicClark
4,&gt; nella sidebar trovate il suo manifesto or...,&gt; nella sidebar trovate il suo manifesto or...,MeccAnon
...,...,...,...
52803,Temo di sì. Non ho mai voluto entrare su alcun...,Temo di sì.\nNon ho mai voluto entrare su alcu...,NaN
52804,no questo mai sentito prima,no questo mai sentito prima,NaN
52805,Benvenuto su r/litigi il sub di riferimento pe...,Benvenuto su r/litigi il sub di riferimento pe...,NaN
52806,ho una brutta notizia per te,> e tuttora non ci sono.\n\nho una brutta not...,NaN
52807,Dimmi,Dimmi,NaN

In [ ]:
#for word in doc:
#    lexeme = doc.vocab[word.text]
#    print(lexeme.text, lexeme.orth, lexeme.shape_, lexeme.prefix_, lexeme.suffix_,
#            lexeme.is_alpha, lexeme.is_digit, lexeme.is_title, lexeme.lang_)

In [ ]:
litigi=litigi.reset_index(drop=True)

In [ ]:
print(litigi.iloc[[2487]]['body_preprocessed'])

2487    Vabbè, è una parola come un'altra, ho preso il...
Name: body_preprocessed, dtype: object

In [ ]:
litigi['sentiment'] = litigi['body_preprocessed'].progress_apply(lambda x: classifier(x)[0]['label'])

  0%|          | 8/362582 [00:00<1:17:06, 78.36it/s]/usr/local/lib/python3.8/dist-packages/transformers/pipelines/base.py:1045: UserWarning: You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
  warnings.warn(
100%|██████████| 362582/362582 [1:10:18<00:00, 85.95it/s]

In [ ]:
#litigi.to_pickle('/content/drive/MyDrive/AI/data/output/litigi_out.pickle')

In [ ]:
litigi[litigi['author']=='ohnoitsalreadytaken'][['author','body','sentiment']]

,author,body,sentiment
98434,ohnoitsalreadytaken,Mettersi a discutere su ritaly é l'equivalente...,neutral
98501,ohnoitsalreadytaken,"Copypasta prossima relazione, tnx ora ho un mo...",neutral
98799,ohnoitsalreadytaken,Vero,neutral
98864,ohnoitsalreadytaken,DOuBle StaNDarDs\n\nGrazie,positive
98867,ohnoitsalreadytaken,"Fegato o milza, sarò la tua squinzia",neutral
...,...,...,...
145028,ohnoitsalreadytaken,Grande,positive
145101,ohnoitsalreadytaken,"Vilnius\n\nPosto di merda, tempo di merda, cib...",negative
145317,ohnoitsalreadytaken,Gruppi whatsapp di stickers con ragazzini turc...,neutral
145319,ohnoitsalreadytaken,"Bello, poi raccontaci se ti va",positive
145345,ohnoitsalreadytaken,"Figurati, uno ha appena messo le tette di bill...",neutral

In [ ]:
#
def dataset_processing():
    '''creates a dataset from pandas df and processes it, returns a df'''
    dataset = Dataset.from_pandas(litigi[['body','author','created_utc','subreddit','id','permalink','link_id','body_preprocessed']])
    # apply the sentiment analysis pipeline to the dataset
    output = classifier(dataset['body_preprocessed'])
    # add the sentiment analysis output to the dataset
    dataset = dataset.add_column('sentiment', output)
    out_df=dataset.to_pandas()

In [ ]:
out_df=litigi

In [ ]:
out_df['sentiment_result']=out_df['sentiment'].apply(lambda x:x['label'])

In [ ]:
out_df['num_words'] = out_df['body_preprocessed'].str.split().apply(len)

In [ ]:
out_df[out_df['author']=='ohnoitsalreadytaken' ][['author','body','sentiment','num_words']]

,author,body,sentiment,num_words
98434,ohnoitsalreadytaken,Mettersi a discutere su ritaly é l'equivalente...,neutral,24
98501,ohnoitsalreadytaken,"Copypasta prossima relazione, tnx ora ho un mo...",neutral,11
98799,ohnoitsalreadytaken,Vero,neutral,1
98864,ohnoitsalreadytaken,DOuBle StaNDarDs\n\nGrazie,positive,3
98867,ohnoitsalreadytaken,"Fegato o milza, sarò la tua squinzia",neutral,7
...,...,...,...,...
145028,ohnoitsalreadytaken,Grande,positive,1
145101,ohnoitsalreadytaken,"Vilnius\n\nPosto di merda, tempo di merda, cib...",negative,23
145317,ohnoitsalreadytaken,Gruppi whatsapp di stickers con ragazzini turc...,neutral,13
145319,ohnoitsalreadytaken,"Bello, poi raccontaci se ti va",positive,6
145345,ohnoitsalreadytaken,"Figurati, uno ha appena messo le tette di bill...",neutral,10

In [ ]:
#myvals = out_df['body_preprocessed'].values.tolist()

#out_df['number_of_words_spacy'] = [len([i for i in nlp(re.sub('</b>|<b>', '', i2)) if not (i.is_space or i.is_punct)]) for i2 in myvals]

In [ ]:
out_df[['sentiment','sentiment_result']]

In [ ]:
df_pivot = pd.pivot_table(
    out_df,
    index='author',
    columns="sentiment",
    aggfunc='size'
)
df_pivot['ratio']=df_pivot['positive']/(df_pivot['negative']+df_pivot['neutral'])
df_pivot

sentiment     negative  neutral  positive     ratio
author
----5----          NaN      1.0       1.0       NaN
--data             1.0      NaN       NaN       NaN
-1mm               1.0      NaN       1.0       NaN
-B-0-             91.0    177.0      19.0  0.070896
-Martika           2.0      1.0       NaN       NaN
...                ...      ...       ...       ...
zia_puppola       12.0     12.0       1.0  0.041667
zingus            14.0     10.0       4.0  0.166667
zizzu2004          2.0      5.0       NaN       NaN
zork824            NaN      1.0       NaN       NaN
zozzonissimo      10.0     13.0       5.0  0.217391

[2142 rows x 4 columns]

In [ ]:
df_pivot.sort_values('positive').to_csv('/content/drive/MyDrive/AI/data/output/user_sentiment_litigi.csv')

In [ ]:
out_df.to_pickle('/content/drive/MyDrive/AI/data/output/out_sentiment.pickle')

In [ ]:
#litigi['sentiment'] = litigi['body_preprocessed'].progress_apply(lambda x: classifier(x)[0]['label'])